# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getPred <- function(C, X) {
    .Call(`_rpkg_getPred`, C, X)
}

getRMSE <- function(v1, v2) {
    .Call(`_rpkg_getRMSE`, v1, v2)
}

getMAE <- function(v1, v2) {
    .Call(`_rpkg_getMAE`, v1, v2)
}

getRho <- function(v1, v2) {
    .Call(`_rpkg_getRho`, v1, v2)
}

getNEDist <- function(X) {
    .Call(`_rpkg_getNEDist`, X)
}

Smplx <- function(X, y, dmat, idxLib, idxPrd, nns) {
    .Call(`_rpkg_Smplx`, X, y, dmat, idxLib, idxPrd, nns)
}

